# Generated by Django 5.0.1 on 2024-05-27 18:39

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "text_block",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", null=True, verbose_name="текст"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog", verbose_name="Картинка"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.",
                        max_length=70,
                        verbose_name="Выбор шаблона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новость",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book_avtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "name_block2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "name_block3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Выбор шаблона"
                    ),
                ),
            ],
            options={
                "verbose_name": "Авторы книг",
                "verbose_name_plural": "Авторы книг",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book_cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "nomer_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Номер сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "book_cat_slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
            ],
            options={
                "verbose_name": "Категории книг",
                "verbose_name_plural": "Категории книг",
                "ordering": ["nomer_id"],
            },
        ),
        migrations.CreateModel(
            name="Otziv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "name_block2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Должность"
                    ),
                ),
                (
                    "text_block",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", null=True, verbose_name="комментарий"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.",
                        max_length=70,
                        verbose_name="Выбор шаблона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзывы о сайте",
                "verbose_name_plural": "Отзывы о сайте",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Prostopages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Заголовок h1",
                    ),
                ),
                (
                    "text_block",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Описание страницы",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="prostopages",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.",
                        max_length=70,
                        verbose_name="Выбор шаблона",
                    ),
                ),
                (
                    "title_us",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Тайтл"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Дескрипшон"),
                ),
            ],
            options={
                "verbose_name": "Простую страницу",
                "verbose_name_plural": "Простые страницы",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog", verbose_name="Картинка"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.",
                        max_length=70,
                        verbose_name="Выбор шаблона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайдер",
                "verbose_name_plural": "Слайдер",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_block",
                    models.CharField(max_length=255, verbose_name="Название книги"),
                ),
                (
                    "opisanie_full",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Описание  полное",
                    ),
                ),
                (
                    "opisanie_mini",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        default="",
                        null=True,
                        verbose_name="Описание краткое",
                    ),
                ),
                (
                    "book_slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Url"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="prostopages",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="prostopages",
                        verbose_name="Картинка-2",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=6,
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=6,
                        null=True,
                        verbose_name="Цена без акции",
                    ),
                ),
                (
                    "procent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=6,
                        null=True,
                        verbose_name="Процент скидки",
                    ),
                ),
                (
                    "skidka",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        default=0,
                        max_digits=6,
                        null=True,
                        verbose_name="Скидка в рублях",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="book_files",
                        verbose_name="Файл fb2",
                    ),
                ),
                (
                    "file2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="book_files",
                        verbose_name="Файл epub",
                    ),
                ),
                (
                    "file3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="book_files",
                        verbose_name="Файл RTF",
                    ),
                ),
                (
                    "file4",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="book_files",
                        verbose_name="Файл Mobi",
                    ),
                ),
                ("futured", models.BooleanField(default=True, verbose_name="Будущее")),
                ("special", models.BooleanField(default=True, verbose_name="Спешл")),
                (
                    "bestseller",
                    models.BooleanField(default=True, verbose_name="Бестселлер"),
                ),
                ("latest", models.BooleanField(default=True, verbose_name="Последние")),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True, max_length=70, verbose_name="Выбор шаблона"
                    ),
                ),
                (
                    "avtors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="avtor_book",
                        to="book.book_avtor",
                        verbose_name="Автор книги",
                    ),
                ),
                (
                    "book_cat",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book.book_cat",
                        verbose_name="книга относится к категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книги",
                "verbose_name_plural": "Книги",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OtzivBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rayting",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Интересно",
                    ),
                ),
                (
                    "rayting2",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "rayting3",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Сюжет",
                    ),
                ),
                (
                    "rayting_seredina",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(0),
                        ],
                        verbose_name="Средний рейтинг",
                    ),
                ),
                (
                    "name_aftor",
                    models.CharField(max_length=255, verbose_name="Имя автора"),
                ),
                (
                    "otziv_plus",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", null=True, verbose_name="Плюсы"
                    ),
                ),
                (
                    "otziv_minus",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", null=True, verbose_name="Минусы"
                    ),
                ),
                (
                    "opisanie",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, default="", null=True, verbose_name="Комментарий"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Перезаписать дату отзыва"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="book.book",
                        verbose_name="выбрать товар по id",
                    ),
                ),
                (
                    "zakazchik",
                    models.ForeignKey(
                        blank=True,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв на книгу",
                "verbose_name_plural": "Отзывы на книги",
                "ordering": ["-id"],
            },
        ),
    ]
