# Generated by Django 5.0.6 on 2024-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file4',
        ),
    ]
